name: Deploy website preview

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Download website source
        uses: actions/checkout@v4

      - name: Prepare website
        run: |
          touch public/.nojekyll

      - name: Upload website
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Publish website
        id: deployment
        uses: actions/deploy-pages@v4
